object Versions {
  const val minSdk = 21
  const val compileSdk = 30
  const val kotlin = "1.5.21"
  const val agp = "7.0.0"
  const val roomMetadataGenerator = "1.2.0"
  const val gradleVersions = "0.38.0"

  const val supportLib = "1.0.0"
  const val recyclerView = "1.0.0"
  const val material = "1.4.0"
  const val cardview = "1.0.0"
  const val room = "2.3.0"
  const val androidXTestExt = "1.1.3"
  const val androidXTest = "1.4.0"
  // Enable Lint partial analysis (android.enableParallelLint) in gradle.properties
  // once Timber supports it.
  const val timber = "4.7.0"
  const val dagger = "2.35.1"
  const val coreTesting = "2.1.0"
  const val moshi = "1.12.0"
  const val retrofit = "2.9.0"
  const val okHttp = "4.9.1"
  const val sentry = "4.3.0"
  const val sentryGradlePlugin = "2.0.1"
  const val flow = "1.0.0-alpha3"
  const val rxJava = "2.2.16"
  const val rxAndroid = "2.1.1"
  const val rxBinding3 = "3.1.0"
  const val rxKotlin = "2.4.0"
  const val rxPreference = "2.0.1"
  const val traceur = "2.2.12"
  const val maskedEditText = "1.0.7"
  const val itemAnimators = "1.0.2"
  const val jbcrypt = "0.3m"
  const val workManager = "2.5.0"
  const val faker = "1.2.8"
  const val truth = "1.1.2"
  const val junit = "4.13.2"
  const val mockitoKotlin = "2.2.0"
  const val junitParams = "1.1.1"
  const val sqliteAndroid = "3.36.0"
  const val playServicesAuth = "19.0.0"
  const val viewPump = "2.0.3"
  const val pinEntryEditText = "2.0.6"
  const val leakCanary = "2.6"
  const val constraintLayout = "2.0.4"
  const val playServicesLocation = "16.0.0"
  const val firebaseConfig = "21.0.0"
  const val firebasePerformance = "20.0.2"
  const val firebasePerformancePlugin = "1.4.0"
  const val googleServices = "4.3.3"
  const val playCore = "1.10.0"
  const val fastScroll = "2.0.0"
  const val mixpanel = "5.6.4"
  const val mobius = "1.5.3"
  const val guava = "28.1-jre" // Used by the "mobius-migration" library ONLY in tests
  const val uuidGenerator = "4.0.1"
  const val flipper = "0.98.0"
  const val soloader = "0.10.1"
  const val asm = "7.2"
  const val ktlint = "0.36.0"
  const val quarantine = "0.3.0"
  const val jackson = "2.12.4"
  const val logback = "1.2.4"
  const val camerax = "1.0.0"
  const val cameraView = "1.0.0-alpha26"
  const val cameraLifecycle = "1.0.0"
  const val zxing = "3.3.3"
  const val paging = "3.0.0"

  // When bumping this dependency verify whether `org.simple.clinic.feature.Feature.ChangeLanguage`
  // can be enabled again.
  const val appcompat = "1.3.0"
  const val lottie = "3.7.2"
  const val desugarJdk = "1.0.9"
  const val signaturePad = "1.3.1"
  const val viewpager2 = "1.0.0"
  const val lint = "27.2.2"
  const val rootbeer = "0.0.9"
  const val mlKitBarcode = "16.2.0"
  const val fragment = "1.3.6"
  const val androidXCoreKtx = "1.6.0"
  const val threetenExtra = "1.6.0"
  const val spotless = "5.6.1"
  const val annotation = "1.2.0"
  const val annotationExperimental = "1.1.0"
  const val coroutines = "1.5.0"
}

val versions = Versions
