package org.simple.clinic.summary

const val SUMMARY_REQCODE_BP_ENTRY = 1
const val SUMMARY_REQCODE_SCHEDULE_APPOINTMENT = 2
const val TYPE_PICKER_SHEET = 3
const val SUMMARY_REQCODE_ALERT_FACILITY_CHANGE = 4
const val BP_REQCODE_ALERT_FACILITY_CHANGE = 5
const val BLOOD_SUGAR_REQCODE_ALERT_FACILITY_CHANGE = 6
const val DRUGS_REQCODE_ALERT_FACILITY_CHANGE = 7
const val ASSIGNED_FACILITY_SELECTION = 8
