package org.simple.clinic.summary

const val SUMMARY_REQCODE_BP_ENTRY = 1
const val SUMMARY_REQCODE_SCHEDULE_APPOINTMENT = 2
const val TYPE_PICKER_SHEET = 3
const val EDIT_PATIENT_ALERT_FACILITY_CHANGE = 4
const val SCHEDULE_APPOINTMENT_ALERT_FACILITY_CHANGE = 5
