name: Auto Request Review

on:
  pull_request:
    types: [ opened, ready_for_review, reopened ]

jobs:
  auto-request-review:
    name: Auto Request Review
    if: |
      github.event.label.name != 'work in progress' &&
      github.event.pull_request.requested_reviewers[0] == null &&
      github.event.pull_request.requested_teams[0] == null &&
      github.event.pull_request.draft == false
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Request Android Devs for review
        uses: necojackarc/auto-request-review@v0.8.0
        with:
          token: ${{ secrets.SERVICES_ACCESS_TOKEN }}
          config: .github/reviewers.yml
      - name: Enable auto merge
        run: gh pr merge --auto -d -s "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
