name: Performance Regression Test Suite

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: benchmark-suite
  cancel-in-progress: true

jobs:
  # reactivecircus/android-emulator-runner@v2 requires MacOS to run on
  # https://github.com/ReactiveCircus/android-emulator-runner
  benchmark_suite:
    runs-on: [ macos-latest ]
    steps:
      - name: Checkout Android source
        uses: actions/checkout@v2

      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Benchmark tests
        id: run-benchmark-tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          arch: x86_64
          disable-animations: true
          script: |
            adb root
            ./gradlew -PmanifestEndpoint=https://api-sandbox.simple.org/api/ installQaDebug installQaDebugAndroidTest lockClocks
            adb shell am instrument -w -e filter org.simple.clinic.benchmark.SelectBenchmarkTests -e benchmark_app_performance true -e dd_client_token ${{ secrets.DD_PERF_CLIENT_TOKEN }} -e dd_application_id ${{ secrets.DD_PERF_APPLICATION_ID }} org.simple.clinic.qa.debug.test/org.simple.clinic.AndroidTestJUnitRunner
            adb uninstall org.simple.clinic.qa.debug
            adb uninstall org.simple.clinic.qa.debug.test
